language: python
python:
  - "3.6"
  
addons:
  sshknownhosts:
  - 104.248.47.163
  
branches:
  only:
  - master
  
env:
  global:
  - REMOTEAPPDIR=/var/www/projectsfair.com/
  - REMOTEUSER=deploy
  - REMOTEHOST=104.248.47.163
  - PORT=8080
  
# command to install dependencies
install:
  - pip install -r requirements.txt
  
before_script:
  - python manage.py makemigrations
  - python manage.py migrate
  - chmod 600 deploy && mv deploy ~/.ssh/idrsa
  
# command to run tests
script:
  - python manage.py test
