language: python
python:
  - "3.6"
branches:
  only:
  - master  
# command to install dependencies
install:
  - pip install -r requirements.txt 
before_script:
  - python manage.py makemigrations
  - python manage.py migrate 
deploy:
  skip_cleanup: true
  provider: heroku
  api_key: 
    secure: $API_KEY
  app: projectsfair
  on:
    repo: robot-lab/projectsfair  
# command to run tests
script:
  - python manage.py test 
